### ISSUE TITLE
error reading NHMInteractionsBank.csv - read [46] columns, but found [24] column definitions

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/natural-history-museum-london-interactions-bank#4]
@edwbaker - just in case you didn't notice the build error at https://travis-ci.org/globalbioticinteractions/natural-history-museum-london-interactions-bank/builds/274314334 (see snippet below).

Please let me know how I can help.

```
7f7558442a25/resource/f84ad9f1-bd0c-4811-8108-8dcd83f224a4/download/NHMInteractionsBank.csv] complete.
19:29:59,646 ERROR StudyImporterForGitHubData:63 - failed to import data from repo [globalbioticinteractions/natural-history-museum-london-interactions-bank]
org.eol.globi.data.StudyImporterException: read [46] columns, but found [24] column definitions.
	at org.eol.globi.data.StudyImporterForMetaTable.importAll(StudyImporterForMetaTable.java:267)
	at org.eol.globi.data.StudyImporterForMetaTable.importTable(StudyImporterForMetaTable.java:127)
	at org.eol.globi.data.StudyImporterForMetaTable.importStudy(StudyImporterForMetaTable.java:67)
	at org.eol.globi.data.StudyImporterForGitHubData.importData(StudyImporterForGitHubData.java:86)
	at org.eol.globi.data.StudyImporterForGitHubData.importData(StudyImporterForGitHubData.java:59)
	at org.eol.globi.tool.GitHubRepoCheck.main(GitHubRepoCheck.java:86)
```

**Comment by edwbaker** [comment]
There seems to be an issue with the NHM Data Portal adding columns, I am discussing this with the developer at the moment.

**Comment by jhpoelen** [comment]
Issue no longer seem to appear, closing issue.
